### ISSUE TITLE
Graphs Download PNG/SVG

### ISSUE THREAD

**Issue by James-A-A** [ToBiDi0410/SpigotMC-Plugins#12]
when downloading a graph as svg or png it defaults to light mode and has white text 
![chart1](https://user-images.githubusercontent.com/50540584/131130117-7fff3bb2-9dbd-4ab1-baba-1e19133fabbd.png)

**Comment by ToBiDi0410** [comment]
![chart1](https://user-images.githubusercontent.com/40767401/132010026-4bcdfda0-4031-4483-86eb-dce522dbd6cd.png)
https://github.com/ToBiDi0410/SpigotMC-Plugins/commit/cc8c0ae153cfaca9d35acf15a96837ba5b6bedbd
