### ISSUE TITLE
GOAT image not showing

### ISSUE THREAD

**Issue by James-A-A** [ToBiDi0410/SpigotMC-Plugins#13]
![8ALayAN8](https://user-images.githubusercontent.com/50540584/131131624-5d6b142a-bba3-4f06-a0c6-98c2db43823f.png)

**Comment by James-A-A** [comment]
Same With FALLING_BLOCK ICON
![XJx8cKGi](https://user-images.githubusercontent.com/50540584/131219518-7a832ac7-3a33-4abe-99a6-365e30030a88.png)

**Comment by ToBiDi0410** [comment]
https://github.com/ToBiDi0410/SpigotMC-Plugins/commit/1c5848626c6865fdd0e5efd6da85ea4b33988bac
