### ISSUE TITLE
Click to copy UUID & username in players tab

### ISSUE THREAD

**Issue by James-A-A** [ToBiDi0410/SpigotMC-Plugins#14]

**Comment by ToBiDi0410** [comment]
Will be added soon.

**Comment by ToBiDi0410** [comment]
![image](https://user-images.githubusercontent.com/40767401/132013129-6029aad3-17ec-4730-8802-39e7424ef4da.png)
https://github.com/ToBiDi0410/SpigotMC-Plugins/commit/e73067a357c7dca755e2780831d18130a18ba9aa
