### ISSUE TITLE
Clicking player multiple times will open player info menu over and over again 

### ISSUE THREAD

**Issue by James-A-A** [ToBiDi0410/SpigotMC-Plugins#15]
![00zwJUOr](https://user-images.githubusercontent.com/50540584/131219356-50955834-8907-4a0e-bd51-732581262a13.png)
when clicking myself 3 times

**Comment by James-A-A** [comment]
Same With worlds tab

**Comment by ToBiDi0410** [comment]
Do you click multiple times, before the Menu is opened or do you close the Menu and open it again?

**Comment by James-A-A** [comment]
Clicking before the menu is open

**Comment by ToBiDi0410** [comment]
https://github.com/ToBiDi0410/SpigotMC-Plugins/commit/b9eae5da990afac31ce13bd4d1b9a8fdaf3da1df
